//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILPathways.ResourceServiceReferenceOLD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceSearchRequest", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResourceSearchRequest : ILPathways.ResourceServiceReferenceOLD.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OutputRelTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartingPageNbrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OutputRelTables {
            get {
                return this.OutputRelTablesField;
            }
            set {
                if ((this.OutputRelTablesField.Equals(value) != true)) {
                    this.OutputRelTablesField = value;
                    this.RaisePropertyChanged("OutputRelTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartingPageNbr {
            get {
                return this.StartingPageNbrField;
            }
            set {
                if ((this.StartingPageNbrField.Equals(value) != true)) {
                    this.StartingPageNbrField = value;
                    this.RaisePropertyChanged("StartingPageNbr");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceGetRequest", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResourceGetRequest : ILPathways.ResourceServiceReferenceOLD.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ResourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ResourceVersionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ResourceId {
            get {
                return this.ResourceIdField;
            }
            set {
                if ((this.ResourceIdField.Equals(value) != true)) {
                    this.ResourceIdField = value;
                    this.RaisePropertyChanged("ResourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ResourceVersionId {
            get {
                return this.ResourceVersionIdField;
            }
            set {
                if ((this.ResourceVersionIdField.Equals(value) != true)) {
                    this.ResourceVersionIdField = value;
                    this.RaisePropertyChanged("ResourceVersionId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ILPathways.ResourceServiceReferenceOLD.ErrorDataContract ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ILPathways.ResourceServiceReferenceOLD.StatusEnumDataContract StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ILPathways.ResourceServiceReferenceOLD.ErrorDataContract Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ILPathways.ResourceServiceReferenceOLD.StatusEnumDataContract Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDataContract", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ErrorDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceSearchResponse", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResourceSearchResponse : ILPathways.ResourceServiceReferenceOLD.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ILPathways.ResourceServiceReferenceOLD.ResourceDataContract[] ResourceListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ILPathways.ResourceServiceReferenceOLD.ResourceDataContract[] ResourceList {
            get {
                return this.ResourceListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceListField, value) != true)) {
                    this.ResourceListField = value;
                    this.RaisePropertyChanged("ResourceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCount {
            get {
                return this.ResultCountField;
            }
            set {
                if ((this.ResultCountField.Equals(value) != true)) {
                    this.ResultCountField = value;
                    this.RaisePropertyChanged("ResultCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRows {
            get {
                return this.TotalRowsField;
            }
            set {
                if ((this.TotalRowsField.Equals(value) != true)) {
                    this.TotalRowsField = value;
                    this.RaisePropertyChanged("TotalRows");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceGetResponse", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResourceGetResponse : ILPathways.ResourceServiceReferenceOLD.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ILPathways.ResourceServiceReferenceOLD.ResourceDataContract ResourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ILPathways.ResourceServiceReferenceOLD.ResourceDataContract Resource {
            get {
                return this.ResourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceField, value) != true)) {
                    this.ResourceField = value;
                    this.RaisePropertyChanged("Resource");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusEnumDataContract", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    public enum StatusEnumDataContract : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceDataContract", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResourceDataContract : ILPathways.ResourceServiceReferenceOLD.BaseContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessRightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLevelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ImportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LRDocIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResouceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ResourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceTypesListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ResourceVersionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RightsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypicalLearningTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessRights {
            get {
                return this.AccessRightsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessRightsField, value) != true)) {
                    this.AccessRightsField = value;
                    this.RaisePropertyChanged("AccessRights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationLevels {
            get {
                return this.EducationLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLevelsField, value) != true)) {
                    this.EducationLevelsField = value;
                    this.RaisePropertyChanged("EducationLevels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Imported {
            get {
                return this.ImportedField;
            }
            set {
                if ((this.ImportedField.Equals(value) != true)) {
                    this.ImportedField = value;
                    this.RaisePropertyChanged("Imported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LRDocId {
            get {
                return this.LRDocIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LRDocIdField, value) != true)) {
                    this.LRDocIdField = value;
                    this.RaisePropertyChanged("LRDocId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageList {
            get {
                return this.LanguageListField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageListField, value) != true)) {
                    this.LanguageListField = value;
                    this.RaisePropertyChanged("LanguageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Modified {
            get {
                return this.ModifiedField;
            }
            set {
                if ((this.ModifiedField.Equals(value) != true)) {
                    this.ModifiedField = value;
                    this.RaisePropertyChanged("Modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResouceUrl {
            get {
                return this.ResouceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResouceUrlField, value) != true)) {
                    this.ResouceUrlField = value;
                    this.RaisePropertyChanged("ResouceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResourceId {
            get {
                return this.ResourceIdField;
            }
            set {
                if ((this.ResourceIdField.Equals(value) != true)) {
                    this.ResourceIdField = value;
                    this.RaisePropertyChanged("ResourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceTypesList {
            get {
                return this.ResourceTypesListField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceTypesListField, value) != true)) {
                    this.ResourceTypesListField = value;
                    this.RaisePropertyChanged("ResourceTypesList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResourceVersionId {
            get {
                return this.ResourceVersionIdField;
            }
            set {
                if ((this.ResourceVersionIdField.Equals(value) != true)) {
                    this.ResourceVersionIdField = value;
                    this.RaisePropertyChanged("ResourceVersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rights {
            get {
                return this.RightsField;
            }
            set {
                if ((object.ReferenceEquals(this.RightsField, value) != true)) {
                    this.RightsField = value;
                    this.RaisePropertyChanged("Rights");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subjects {
            get {
                return this.SubjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectsField, value) != true)) {
                    this.SubjectsField = value;
                    this.RaisePropertyChanged("Subjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Submitter {
            get {
                return this.SubmitterField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmitterField, value) != true)) {
                    this.SubmitterField = value;
                    this.RaisePropertyChanged("Submitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypicalLearningTime {
            get {
                return this.TypicalLearningTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypicalLearningTimeField, value) != true)) {
                    this.TypicalLearningTimeField = value;
                    this.RaisePropertyChanged("TypicalLearningTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseContract", Namespace="http://schemas.datacontract.org/2004/07/IllinoisPathways.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ILPathways.ResourceServiceReferenceOLD.ResourceDataContract))]
    public partial class BaseContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> LastUpdatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastUpdatedByNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate {
            get {
                return this.LastUpdateDateField;
            }
            set {
                if ((this.LastUpdateDateField.Equals(value) != true)) {
                    this.LastUpdateDateField = value;
                    this.RaisePropertyChanged("LastUpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> LastUpdatedBy {
            get {
                return this.LastUpdatedByField;
            }
            set {
                if ((this.LastUpdatedByField.Equals(value) != true)) {
                    this.LastUpdatedByField = value;
                    this.RaisePropertyChanged("LastUpdatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastUpdatedByName {
            get {
                return this.LastUpdatedByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastUpdatedByNameField, value) != true)) {
                    this.LastUpdatedByNameField = value;
                    this.RaisePropertyChanged("LastUpdatedByName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceServiceReferenceOLD.IResourceService")]
    public interface IResourceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/ResourceGet", ReplyAction="http://tempuri.org/IResourceService/ResourceGetResponse")]
        ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse ResourceGet(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceService/ResourceGet", ReplyAction="http://tempuri.org/IResourceService/ResourceGetResponse")]
        System.IAsyncResult BeginResourceGet(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request, System.AsyncCallback callback, object asyncState);
        
        ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse EndResourceGet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceService/ResourceSearch", ReplyAction="http://tempuri.org/IResourceService/ResourceSearchResponse")]
        ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse ResourceSearch(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IResourceService/ResourceSearch", ReplyAction="http://tempuri.org/IResourceService/ResourceSearchResponse")]
        System.IAsyncResult BeginResourceSearch(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request, System.AsyncCallback callback, object asyncState);
        
        ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse EndResourceSearch(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceServiceChannel : ILPathways.ResourceServiceReferenceOLD.IResourceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResourceGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResourceSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceServiceClient : System.ServiceModel.ClientBase<ILPathways.ResourceServiceReferenceOLD.IResourceService>, ILPathways.ResourceServiceReferenceOLD.IResourceService {
        
        private BeginOperationDelegate onBeginResourceGetDelegate;
        
        private EndOperationDelegate onEndResourceGetDelegate;
        
        private System.Threading.SendOrPostCallback onResourceGetCompletedDelegate;
        
        private BeginOperationDelegate onBeginResourceSearchDelegate;
        
        private EndOperationDelegate onEndResourceSearchDelegate;
        
        private System.Threading.SendOrPostCallback onResourceSearchCompletedDelegate;
        
        public ResourceServiceClient() {
        }
        
        public ResourceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ResourceGetCompletedEventArgs> ResourceGetCompleted;
        
        public event System.EventHandler<ResourceSearchCompletedEventArgs> ResourceSearchCompleted;
        
        public ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse ResourceGet(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request) {
            return base.Channel.ResourceGet(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginResourceGet(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResourceGet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse EndResourceGet(System.IAsyncResult result) {
            return base.Channel.EndResourceGet(result);
        }
        
        private System.IAsyncResult OnBeginResourceGet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request = ((ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest)(inValues[0]));
            return this.BeginResourceGet(request, callback, asyncState);
        }
        
        private object[] OnEndResourceGet(System.IAsyncResult result) {
            ILPathways.ResourceServiceReferenceOLD.ResourceGetResponse retVal = this.EndResourceGet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResourceGetCompleted(object state) {
            if ((this.ResourceGetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResourceGetCompleted(this, new ResourceGetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResourceGetAsync(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request) {
            this.ResourceGetAsync(request, null);
        }
        
        public void ResourceGetAsync(ILPathways.ResourceServiceReferenceOLD.ResourceGetRequest request, object userState) {
            if ((this.onBeginResourceGetDelegate == null)) {
                this.onBeginResourceGetDelegate = new BeginOperationDelegate(this.OnBeginResourceGet);
            }
            if ((this.onEndResourceGetDelegate == null)) {
                this.onEndResourceGetDelegate = new EndOperationDelegate(this.OnEndResourceGet);
            }
            if ((this.onResourceGetCompletedDelegate == null)) {
                this.onResourceGetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResourceGetCompleted);
            }
            base.InvokeAsync(this.onBeginResourceGetDelegate, new object[] {
                        request}, this.onEndResourceGetDelegate, this.onResourceGetCompletedDelegate, userState);
        }
        
        public ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse ResourceSearch(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request) {
            return base.Channel.ResourceSearch(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginResourceSearch(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResourceSearch(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse EndResourceSearch(System.IAsyncResult result) {
            return base.Channel.EndResourceSearch(result);
        }
        
        private System.IAsyncResult OnBeginResourceSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request = ((ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest)(inValues[0]));
            return this.BeginResourceSearch(request, callback, asyncState);
        }
        
        private object[] OnEndResourceSearch(System.IAsyncResult result) {
            ILPathways.ResourceServiceReferenceOLD.ResourceSearchResponse retVal = this.EndResourceSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResourceSearchCompleted(object state) {
            if ((this.ResourceSearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResourceSearchCompleted(this, new ResourceSearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResourceSearchAsync(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request) {
            this.ResourceSearchAsync(request, null);
        }
        
        public void ResourceSearchAsync(ILPathways.ResourceServiceReferenceOLD.ResourceSearchRequest request, object userState) {
            if ((this.onBeginResourceSearchDelegate == null)) {
                this.onBeginResourceSearchDelegate = new BeginOperationDelegate(this.OnBeginResourceSearch);
            }
            if ((this.onEndResourceSearchDelegate == null)) {
                this.onEndResourceSearchDelegate = new EndOperationDelegate(this.OnEndResourceSearch);
            }
            if ((this.onResourceSearchCompletedDelegate == null)) {
                this.onResourceSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResourceSearchCompleted);
            }
            base.InvokeAsync(this.onBeginResourceSearchDelegate, new object[] {
                        request}, this.onEndResourceSearchDelegate, this.onResourceSearchCompletedDelegate, userState);
        }
    }
}
