//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILPathways.Controls.Rubrics {
    
    
    public partial class RubricCore {
        
        /// <summary>
        /// rubricInfrastructure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl rubricInfrastructure;
        
        /// <summary>
        /// AchieveRubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ILPathways.Controls.Rubrics.AchieveRubric AchieveRubric;
        
        /// <summary>
        /// CCSSMathRubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ILPathways.Controls.Rubrics.CCSSMathRubric CCSSMathRubric;
        
        /// <summary>
        /// CCSSELAK_2Rubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ILPathways.Controls.Rubrics.CCSSELAK_2Rubric CCSSELAK_2Rubric;
        
        /// <summary>
        /// CCSSELA3_12Rubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ILPathways.Controls.Rubrics.CCSSELA3_12Rubric CCSSELA3_12Rubric;
        
        /// <summary>
        /// selectRubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl selectRubric;
        
        /// <summary>
        /// rblSelectRubric control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblSelectRubric;
        
        /// <summary>
        /// btnSubmitScores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSubmitScores;
        
        /// <summary>
        /// hdnScoreHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdnScoreHolder;
    }
}
