//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_GradeLevel
    {
        public Codes_GradeLevel()
        {
            this.Resource_GradeLevel = new HashSet<Resource_GradeLevel>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string AliasValues { get; set; }
        public string NsdlTitle { get; set; }
        public Nullable<int> AgeLevel { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPathwaysLevel { get; set; }
        public Nullable<bool> IsK12Level { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AlignmentUrl { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> WarehouseTotal { get; set; }
        public string GradeRange { get; set; }
        public string GradeGroup { get; set; }
        public Nullable<int> PathwaysEducationLevelId { get; set; }
        public Nullable<bool> IsEducationBand { get; set; }
        public Nullable<int> FromAge { get; set; }
        public Nullable<int> ToAge { get; set; }
    
        public virtual ICollection<Resource_GradeLevel> Resource_GradeLevel { get; set; }
    }
}
