//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionOfUse
    {
        public int Id { get; set; }
        public string Summary { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SortOrderAuthoring { get; set; }
        public string Url { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> ConditionOfUseCategory { get; set; }
        public Nullable<int> WarehouseTotal { get; set; }
        public string MiniIconUrl { get; set; }
    }
}
