//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patron
    {
        public Patron()
        {
            this.Patron_Following = new HashSet<Patron_Following>();
            this.Patron_Following1 = new HashSet<Patron_Following>();
            this.Patron_ExternalAccount = new HashSet<Patron_ExternalAccount>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public string ExternalIdentifier { get; set; }
    
        public virtual Patron_Profile Patron_Profile { get; set; }
        public virtual ICollection<Patron_Following> Patron_Following { get; set; }
        public virtual ICollection<Patron_Following> Patron_Following1 { get; set; }
        public virtual ICollection<Patron_ExternalAccount> Patron_ExternalAccount { get; set; }
    }
}
