//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publish_Pending
    {
        public int Id { get; set; }
        public Nullable<int> ResourceIntId { get; set; }
        public Nullable<int> ResourceVersionIntId { get; set; }
        public string DocId { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string LrEnvelope { get; set; }
    }
}
