//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Tag
    {
        public int Id { get; set; }
        public int ResourceIntId { get; set; }
        public int TagValueId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string OriginalValue { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Codes_TagValue Codes_TagValue { get; set; }
    }
}
