//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Version
    {
        public int Id { get; set; }
        public Nullable<int> ResourceIntId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DocId { get; set; }
        public string Publisher { get; set; }
        public string Creator { get; set; }
        public string Rights { get; set; }
        public string AccessRights { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Submitter { get; set; }
        public Nullable<System.DateTime> Imported { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string TypicalLearningTime { get; set; }
        public Nullable<bool> IsSkeletonFromParadata { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Requirements { get; set; }
        public string SortTitle { get; set; }
        public string Schema { get; set; }
        public Nullable<int> AccessRightsId { get; set; }
        public Nullable<int> InteractivityTypeId { get; set; }
        public string InteractivityType { get; set; }
        public System.Guid RowId { get; set; }
    }
}
