//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOERBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardBody_Node
    {
        public StandardBody_Node()
        {
            this.StandardBody_NodeGradeLevel = new HashSet<StandardBody_NodeGradeLevel>();
            this.StandardBody_Subject = new HashSet<StandardBody_Subject>();
            this.Resource_Standard = new HashSet<Resource_Standard>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string LevelType { get; set; }
        public string NotationCode { get; set; }
        public string Description { get; set; }
        public string StandardUrl { get; set; }
        public string AltUrl { get; set; }
        public string StandardGuid { get; set; }
        public Nullable<int> WarehouseTotal { get; set; }
        public string GradeLevels { get; set; }
    
        public virtual ICollection<StandardBody_NodeGradeLevel> StandardBody_NodeGradeLevel { get; set; }
        public virtual ICollection<StandardBody_Subject> StandardBody_Subject { get; set; }
        public virtual ICollection<Resource_Standard> Resource_Standard { get; set; }
    }
}
