<%@ Page Title="Illinois Open Educational Resources - Privacy Policy" Language="C#" AutoEventWireup="true" CodeBehind="PrivacyPolicy.aspx.cs" Inherits="IOER.Pages.PrivacyPolicy" MasterPageFile="/Masters/Responsive.Master" %>

<asp:Content ContentPlaceHolderID="HeadContent" runat="server">
  <link rel="stylesheet" href="/styles/common2.css" />
</asp:Content>
<asp:Content ContentPlaceHolderID="BodyContent" runat="server">
  <style type="text/css">
    #policy h3 { margin-top: 20px; font-size: 24px;}
      p, p span, p a, li, li em, p span, p strong {
          font-size: 18px;
      }
  </style>
  <div id="content">
    <h1 class="isleH1">Privacy Policy</h1>
    <div id="policy">

      <span >Effective Date: June 6, 2013</span>
      <h2 class="isleH2">ILLINOIS SHARED LEARNING ENVIRONMENT PRIVACY POLICY</h2>
      <p style="text-align: justify;">Illinois Shared Learning Environment ("<strong>ISLE</strong>", "<strong>we</strong>", "<strong>our</strong>" or "<strong>us</strong>") values your privacy.&nbsp; At ILsharedlearning.org we provide tools and resources that support personalized learning for lifelong learners in Illinois.&nbsp; In this Privacy Policy ("<strong>Policy</strong>"), we describe how we collect, use, and disclose information that we obtain about visitors to our web site ILsharedlearning.org (the "<strong>Site</strong>") and the services available through our Site (collectively, the "<strong>Services</strong>").</p>
      <p style="text-align: justify;">By visiting the Site, or using any of our Services, you agree that your information will be handled as described in this Policy.&nbsp; Your use of our Site or Services, and any dispute over privacy, is subject to this Policy and our <a title="Terms of Use Web Page" href="/pages/termsofuse.aspx">Terms of Use</a>,<strong><em> </em></strong>including its applicable limitations on damages and the resolution of disputes.&nbsp; The Terms of Use are incorporated by reference into this Policy.</p>
      <p style="text-align: justify;">The Illinois Shared Learning Environment ("<strong>ISLE</strong>") is an intergovernmental consortium formed by an agreement among the following governmental entities:&nbsp; Illinois State Board of Education (ISBE) and Illinois Department of Commerce and Economic Opportunity (DCEO), as the project's sponsors ("<strong>Project Sponsors</strong>"); and the IlliniCloud Cooperative, the Board of Trustees of the University of Illinois, the Board of Trustees of Northern Illinois University and the Board of Trustees of Southern Illinois University, as project partners ("<strong>Project Partners</strong>").&nbsp; In this Policy, any references to ISLE include ISBE and DCEO, acting jointly as Project Sponsors.</p>
      <h3>Policies for Individuals Under 13 years of Age.</h3>
      <p style="text-align: justify;">ISLE does not knowingly collect or store any personal information about children under the age of 13.&nbsp; The ISLE administrator will reject a registration request if it has knowledge that a person is under the age of 13.&nbsp; If you are under the age of 13, you are not authorized to provide personal information. </p>
      <h3>What Information Do We Collect About You and Why?</h3>
      <p style="text-align: justify;">We may collect information about you directly from you and from third parties, as well as automatically through your use of our Site or Services.</p>
      <h3>Information We Collect Directly From You.</h3>
      <p>Certain areas and features of our Site and Services may require registration.&nbsp; To register you must provide information including, your name, email address and organization affiliation (e.g., school district, workforce development partner, etc.).&nbsp; We also may collect additional information from you, including other information that would help provide you specific information geared toward your needs; however, you are not required to provide us with this optional information.</p>
      <h3>Information that We Collect About You from Social Networking Sites.</h3>
      <p>You may log into our Site and Services through your social networking accounts, including Facebook, LinkedIn, Twitter, Google and Edmodo.&nbsp; When you engage with our Site and Services through third party social networking sites, you may allow us to have access to certain information from your social media profile (e.g., name, e-mail address, photo, gender, birthday, location, your list of friends, people you follow and/or who follow you, the posts or the 'likes' you make). We may also obtain non-personal information from your interaction with our Site and Services and request certain permissions from you in conjunction with your use of the social networking site.&nbsp; The permissions that we request and the information that we collect about you will vary based on the particular social networking site.</p>
      <p style="text-align: justify;">When you provide information from your social media account, it can help enable us to do things like: (1) give you exclusive content; (2) personalize your online experience with us; and (3) contact you through the social networking sites.&nbsp; By doing so, you consent to the use of this information in accordance with our Policy.&nbsp; In addition, when you provide information to us through an application, on our Sites, or on social networking sites, it may be publicly viewed by other members of these sites and we cannot prevent further use of the information by third parties.</p>
      <p style="text-align: justify;">We store the information that we receive from social networking sites, including Facebook, LinkedIn, Twitter, Google and Edmodo, with other information that we collect from you or receive about you. </p>
      <p style="text-align: justify;">Any third-party social networking site controls the information it collects from you.&nbsp; For information about how they may use and disclose your information, including any information you make public, please consult their respective privacy policies.&nbsp; We have no control over how any third party site uses or discloses the information it collects about you. </p>
      <h3>Information We Collect Automatically.</h3>
        <p>We may automatically collect the following information about your use of our Site or Services through cookies, web beacons, and other technologies: your domain name; your browser type and operating system; web pages you view; links you click; your IP address; the length of time you visit our Site and or use our Services; the referring URL (or the webpage that led you to our Site); and the following: access time, browser type, domain name, IP address, page views and referring URL.&nbsp; Please see the section "Our Use of Cookies and Other Tracking Mechanisms" below for more information.</p>
      <h3>How We Use Your Information</h3>
      <p style="text-align: justify;">We use the information that we gather about you for the following purposes: </p>
      <ul style="text-align: justify;"><li>To provide our Services to you, to communicate with you about your use of our Services, to respond to your inquiries, to fulfill your requests and for other service purposes.</li><li>To tailor the content and information that we may send or display to you, to offer personalized help and instructions and to otherwise personalize your experiences while using the Site or our Services.</li><li>For informational purposes.&nbsp; For example, we may use your information, such as your email address, to send you news and newsletters or to otherwise contact you about information, training or events we think may interest you.</li><li>To better understand how users access and use our Site and Services, both on an aggregated and individualized basis.</li><li>In order to improve our Site and Services and respond to user desires and preferences.</li><li>For research and analytical purposes.</li><li>If you have granted us permission, to post to your Facebook Wall.</li></ul>
      <h3>How We Share Your Information</h3>
      <p style="text-align: justify;">We may share the information that we collect about you, including personal information, as follows: </p>
      <ul style="text-align: justify;"><li><strong><em>Other Users.&nbsp;</em></strong> Your user name and any information that you post to our Site, including, reviews, comments, images and text will be available to, and searchable by, all users of the Site and Services.</li><li><strong><em>Project Partners.&nbsp;</em></strong> We may disclose the information we collect from you to current Project Partners and any future project partners; however, if we do so, their use and disclosure of your personal information will be subject to this Policy.</li><li><strong><em>Facebook Users.</em></strong>&nbsp; If you grant us permission to post on your Wall, a notification will be visible on your Facebook page telling your friends that you have started using our Site and Services.&nbsp; Our Facebook application also will be visible on your Facebook page under "applications."</li><li><strong><em>S</em></strong><strong><em>ervice Providers.&nbsp;</em></strong> We may disclose the information we collect from you to third party vendors, service providers, contractors or agents who perform functions on our behalf; however, if we do so, their use and disclosure of your personal information will be subject to this Policy.</li><li><strong><em>Transfers of ISLE Operations.&nbsp; </em></strong>If the operations and administration of ISLE is transferred to another governmental or nonprofit entity, we may transfer the information we have collected from you to the other entity.</li><li><strong><em>In Response to Legal Process.&nbsp;</em></strong> We may disclose the information we collect from you in order to comply with or as required by the law, a judicial proceeding, court order, or other legal process, such as in response to a court order or a subpoena.</li><li><strong><em>To Protect Us and Others.&nbsp;</em></strong> We may disclose the information we collect from you where we believe it is necessary to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the safety of any person, violations of our Terms of Use or this Policy, or as evidence in litigation in which ISLE is involved.</li><li><strong><em>Aggregate and De-Identified Information.</em></strong>&nbsp; We may share aggregate or de-identified information about users with third parties for analytical, research or similar purposes. </li></ul>
      <h3>Our Use of Cookies and Other Tracking Mechanisms</h3>
      <p style="text-align: justify;">We use cookies and other tracking mechanisms to track information about your use of our Site or Services.&nbsp; We may combine this information with other personal information we collect from you.&nbsp; Cookies are alphanumeric identifiers that we transfer to your computer's hard drive through your web browser for record-keeping purposes. Some cookies allow us to make it easier for you to navigate our Site and Services, while others are used to enable a faster log-in process or to allow us to track your activities at our Site and Service.&nbsp; There are two types of cookies: session and persistent cookies.</p>
      <p style="text-align: justify;"><span style="text-decoration: underline;">Session Cookies.&nbsp;</span> Session cookies exist only during an online session.&nbsp; They disappear from your computer when you close your browser or turn off your computer.&nbsp; We use session cookies to allow our systems to uniquely identify you during a session or while you are logged into the Site.&nbsp; This allows us to process your online transactions and requests and verify your identity, after you have logged in, as you move through our Site. </p>
      <p style="text-align: justify;"><span style="text-decoration: underline;">Persistent cookies.&nbsp;</span> Persistent cookies remain on your computer after you have closed your browser or turned off your computer.&nbsp; We use persistent cookies to track aggregate and statistical information about user activity.</p>
      <h3>Third Party Cookies</h3>
      <p>We may engage third parties to track and analyze Site data.&nbsp; We use the data collected by such third parties to help us administer and improve the quality of the Site and to analyze Site usage.&nbsp; Such third parties may combine the information that we provide about you with other information that they have collected.&nbsp; This Policy does not cover such third parties' use of the data.</p>
      <h3>Disabling Cookies.</h3>
      <p>Most web browsers automatically accept cookies, but if you prefer, you can edit your browser options to block them in the future.&nbsp; The "Help" portion of the toolbar on most browsers will tell you how to prevent your computer from accepting new cookies, how to have the browser notify you when you receive a new cookie or how to disable cookies altogether.&nbsp; Visitors to our Site who disable cookies will be able to browse certain areas of the Site, but some features may not function.</p>
      <h3>Third Party Analytics.</h3>
      <p>We use automated devices and applications, such as Google Analytics, to evaluate usage of our Site and our Services.&nbsp; We also may use other analytic means to evaluate our Services.&nbsp; We use these tools to help us improve our Services, performance and user experiences.&nbsp; We do not share your personal information with these third parties. </p>
      <h3>User Generated Content</h3>
      <p style="text-align: justify;">We invite you to post content on our Site, including your comments, pictures, and any other information that you would like to be available on our Site.&nbsp; If you post content to our Site, all of the information that you post may be available to all visitors to our Site and all registered users on our Site. If you post your own content on our Site or Services, your posting may become public and ISLE cannot prevent such information from being used in a manner that may violate this Policy, the law or your personal privacy.</p>
      <h3>Third-Party Links</h3>
      <p style="text-align: justify;">Our Site and Services may contain links to third party web sites.&nbsp; Any access to and use of such linked web sites is not governed by this Policy, but instead is governed by the privacy policies of those third party web sites.&nbsp; We are not responsible for the information practices of such third party web sites.&nbsp; The inclusion of a link on the Site does not imply endorsement of the linked site by us or our Project Partners.</p>
      <h3>Security of My Personal Information.</h3>
      <p style="text-align: justify;">Please be aware that the security of the Site and Services is not guaranteed.&nbsp; </p>
      <p style="text-align: justify;">You should take steps to protect against unauthorized access to your password, phone and computer by, among other things, signing off after using a shared computer, choosing a robust password that nobody else knows or can easily guess and keeping your log-in and password private.&nbsp; We are not responsible for any lost, stolen or compromised passwords or for any activity on your account via unauthorized password activity.</p>
      <h3>Access To My Personal Information</h3>
      <p style="text-align: justify;">You may modify personal information that you have submitted by logging into your account and updating your profile information. Please note that copies of information that you have updated, modified or deleted may remain viewable in cached and archived pages of the Site for a period of time.</p>
      <h3>What Choices Do I Have Regarding Use of My Personal Information?</h3>
      <p style="text-align: justify;">We may send periodic informational emails to you. You may opt-out of such communications by following the opt-out instructions contained in the e-mail.&nbsp; Please note that it may take up to ten (10) business days for us to process opt-out requests.&nbsp; If you opt-out of receiving emails about recommendations or other information we think may interest you, we may still send you e-mails about your account or any Services you have requested or received from us.</p>
      <h3>Contact Us</h3>
      <p style="text-align: justify;">If you have questions about the privacy aspects of our Services or would like to make a complaint, please contact us at <span style="text-decoration: underline;"><a href="mailto:info@islesharedlearning.org">info@islesharedlearning.org</a>.</span>&nbsp;&nbsp;<br></p>
      <h3>Changes to this Policy</h3>
      <p style="text-align: justify;">This Policy is current as of the Effective Date set forth above.&nbsp; We may change this Policy from time to time, so please be sure to check back periodically.&nbsp; We will post any changes to this Policy on our Site, at <a href="/pages/privacypolicy.aspx" title="Privacy policy">http://ioer.ilsharedlearning.org/pages/privacypolicy.aspx​</a>.&nbsp; If we make any changes to this Policy that materially affect our practices with regard to the personal information we have previously collected from you, we will endeavor to provide you with notice in advance of such change by highlighting the change on our Site or by sending an email to you at the email address that you have registered with us.​</p>

    </div><!--/policy-->
  </div><!--/content-->
</asp:Content>