<%@ Page Title="Illinois Open Educational Resources - Terms of Use" Language="C#" AutoEventWireup="true" CodeBehind="TermsOfUse.aspx.cs" Inherits="IOER.Pages.TermsOfUse" MasterPageFile="/Masters/Responsive.Master" %>

<asp:Content ContentPlaceHolderID="HeadContent" runat="server">
  <link rel="stylesheet" href="/styles/common2.css" />
</asp:Content>
<asp:Content ContentPlaceHolderID="BodyContent" runat="server">
  <style type="text/css">
    #terms h3 { margin-top: 20px; font-size: 24px;}
      p, p span, p a, li, li em, p span, p strong {
          font-size: 18px;
      }
  </style>

  <div id="content">
    <h1 class="isleH1">Terms of Use</h1>
    <div id="terms">

      <span >Effective Date: June 6, 2013</span>
      <h2 class="isleH2">ILLINOIS SHARED LEARNING ENVIRONMENT ("ISLE", "WE", "OUR" OR "US") TERMS OF USE</h2>
      <p style="text-align: justify;">THESE TERMS AND CONDITIONS (THE "<strong>TERMS</strong>") ARE A LEGAL CONTRACT BETWEEN YOU AND ISLE (AS DEFINED BELOW).&nbsp; THESE TERMS EXPLAIN HOW YOU ARE PERMITTED TO USE THE WEB SITE LOCATED AT ILSHAREDLEARNING.ORG (THE "<strong>SITE</strong>").&nbsp; BY USING THE SITE, YOU ARE AGREEING TO ALL OF THESE TERMS; IF YOU DO NOT AGREE WITH ANY OF THESE TERMS, DO NOT ACCESS OR OTHERWISE USE THE SITE OR ANY INFORMATION CONTAINED ON THE SITE.</p>
      <h3>ISLE</h3>
      <p style="text-align: justify;">The Illinois Shared Learning Environment ("<strong>ISLE</strong>") is an intergovernmental consortium formed by an agreement among the following governmental entities:&nbsp; Illinois State Board of Education (ISBE) and Illinois Department of Commerce and Economic Opportunity (DCEO), as the project's sponsors ("<strong>Project Sponsors</strong>"); and the IlliniCloud Cooperative, the Board of Trustees of the University of Illinois, the Board of Trustees of Northern Illinois University and the Board of Trustees of Southern Illinois University, as project partners ("<strong>Project Partners</strong>").&nbsp; In this Policy, any references to ISLE include ISBE and DCEO, acting jointly as Project Sponsors.</p>
      <h3>Changes.</h3>
      <p style="text-align: justify;">ISLE has the right to make changes to the content offered through the Site at any time.&nbsp; ISLE can change, update, or add or remove provisions of these Terms, at any time by posting the updated Terms on the Site.&nbsp; By using the Site after ISLE has updated the Terms, you are agreeing to all the updated Terms; if you do not agree with any of the updated Terms, you must stop using the Site.</p>
      <h3>General Use.</h3>
      <p style="text-align: justify;">ISLE provides content through the Site that is copyrighted and/or trademarked work of ISLE or ISLE's third-party licensors and suppliers or other users of the Site (collectively, the "<strong>Materials</strong>").&nbsp; Materials may include logos, graphics, video, images, software and other content.</p>
      <p style="text-align: justify;">ISLE hereby grants you a limited, personal, non-exclusive and non-transferable license to use and to display the Materials and to use the Site solely for your personal use.&nbsp; Except for the foregoing license, you have no other rights in the Site or any Materials and you may not modify, edit, copy, reproduce, create derivative works of, reverse engineer, alter, enhance or in any way exploit any of the Site or Materials in any manner.</p>
      <p style="text-align: justify;">If you breach any of these Terms, the above license will terminate automatically and you must immediately destroy any downloaded or printed Materials.</p>
      <h3>Using the Site and the Services on the Site.</h3>
      <p style="text-align: justify;">You need not register with ISLE to visit and view the Site.&nbsp; However, in order to access certain password-restricted areas of the Site and to use certain Materials offered on and through the Site, you must register for an account and receive a password.&nbsp; ISLE has the right to approve or reject the requested registration, in ISLE's sole discretion.</p>
      <p style="text-align: justify;">In the future, ISLE may provide you with the ability to register for an account on the Site using your existing account and log-in credentials through third party web sites, such as, Facebook, Linked In, Twitter, Edmodo and Google.</p>
      <p style="text-align: justify;">You are responsible for maintaining the confidentiality of your passwords, and you are responsible for all activities that occur using your passwords. You agree not to share your passwords, let others access or use your passwords or do anything else that might jeopardize the security of your passwords.&nbsp; You agree to notify ISLE if any of your passwords are lost or stolen, if you are aware of any unauthorized use of your passwords on the Site or if you know of any other breach of security in relation to the Site.</p>
      <p style="text-align: justify;">All the information that you provide when registering for an account and otherwise through the Site must be accurate, complete and up to date.&nbsp; You may change, correct or remove any information from your account by either logging into your account directly and making the desired changes or contacting ISLE using the contact information at the end of these Terms requesting that we make the change.</p>
      <p style="text-align: justify;">If you register for a "beta account" or other pre-release version of the Materials on the Site ("<strong>Beta Release</strong>"), you acknowledge and agree that the Beta Release may contain, in ISLE's sole discretion, more or fewer features or different licensing terms than a subsequent release version of the Materials that may be offered through the Site.&nbsp; You acknowledge and agree that any "beta account" will automatically convert to a production release version account upon the launch date of the Materials to the public ("<strong>Public Launch Date</strong>").&nbsp; If you do not desire to continue using the Materials after the Public Launch Date, you may contact ISLE to delete your account in accordance with the terms and conditions governing deletion of personal information set forth in ISLE's <a href="/pages/privacypolicy.aspx">Privacy Policy</a>. &nbsp; While ISLE generally intends to distribute public release versions of the Materials on the Site, ISLE reserves the right not to release later public release versions of any Beta Release.&nbsp; Without limiting any disclaimer of warranty or other limitation stated herein, you agree that any Beta Release may contain errors affecting its proper operation.&nbsp; BY ACCEPTING THESE TERMS, YOU ACKNOWLEDGE AND AGREE THAT USE OF A BETA RELEASE MAY EXHIBIT SPORADIC DISRUPTIONS THAT HAVE THE POTENTIAL TO DISRUPT YOUR USE OF THE SITE IN GENERAL AND ANY SERVICES THAT MAY BE OFFERED THROUGH THE SITE.&nbsp; ISLE SPECIFICALLY DISCLAIMS ALL DAMAGES RESULTING FROM YOUR USE OF ANY BETA RELEASE.</p>
      <h3>Links to Third Party Sites.</h3>
      <p style="text-align: justify;">The Site may be linked to third party web sites (collectively, "<strong>Third Party Sites</strong>").&nbsp; Certain areas of the Site may allow you to interact and/or conduct transactions with such Third Party Sites, and, if applicable, allow you to configure your privacy settings in your Third Party Site account to permit your activities on the Site to be shared with your contacts in your Third Party Site account and, in certain situations, you may be transferred to a Third Party Site through a link but it may appear that you are still on the Site.&nbsp; In any case, you acknowledge and agree that the Third Party Sites may have different privacy policies and terms and conditions and/or user guides and business practices than ISLE, and you further acknowledge and agree that your use of such Third Party Sites is governed by the respective Third Party Site privacy policy, terms and conditions and/or user guides.&nbsp; You hereby agree to comply with any and all privacy policies, terms and conditions and users guides of any Third Party Sites.&nbsp; ISLE is providing links to the Third Party Sites to you as a convenience, and ISLE does not verify, make any representations or take responsibility for such Third Party Sites, including, without limitation, the truthfulness, accuracy, quality or completeness of the content, services, links displayed and/or any other activities conducted on or through such Third Party Sites. YOU AGREE THAT ISLE WILL NOT, UNDER ANY CIRCUMSTANCES, BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY GOODS, SERVICES, INFORMATION, RESOURCES AND/OR CONTENT AVAILABLE ON OR THROUGH ANY THIRD PARTY SITES AND/OR THIRD-PARTY DEALINGS OR COMMUNICATIONS, OR FOR ANY HARM RELATED THERETO, OR FOR ANY DAMAGES OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH YOUR USE OR RELIANCE ON THE CONTENT OR BUSINESS PRACTICES OF ANY THIRD PARTY.&nbsp; Any reference on the Site to any product, service, publication, institution, organization of any third party entity or individual does not constitute or imply ISLE's endorsement or recommendation.</p>
      <h3>Submissions.</h3>
      <p style="text-align: justify;">You are responsible for the information, opinions, messages, comments, photos, videos, graphics, sounds and other content or material that you submit, upload, post or otherwise make available on or through the Site (each a "<strong>Submission</strong>").&nbsp; You may not upload, post or otherwise make available on the Site any material protected by copyright, trademark, or any other proprietary right without the express permission of the owner of such copyright, trademark or other proprietary right, and the burden of determining whether any material is protected by any such right is on you.&nbsp; You shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights, violation of contract, privacy or publicity rights or any other harm resulting from any Submission that you make.&nbsp; You have full responsibility for each Submission you make, including, without limitation, its legality, reliability and appropriateness.</p>
      <p style="text-align: justify;">Unless otherwise explicitly stated herein or in ISLE's <a href="/pages/privacypolicy.aspx">Privacy Policy</a>, you agree that any Submission provided by you in connection with the Site is provided on a non-proprietary and non-confidential basis.&nbsp; You hereby grant to ISLE a non-exclusive, perpetual, irrevocable, royalty-free, fully paid-up, worldwide license (including, without limitation, the right to sublicense through multiple tiers) to use, reproduce, process, adapt, publicly perform, publicly display, modify, prepare derivative works, publish, transmit and distribute each of your Submissions, or any portion thereof, in any form, medium or distribution method now known or hereafter existing, known or developed, and authorize others to use the Submissions.&nbsp; We have the right to modify or adapt your Submissions in order to transmit, display or distribute them over computer networks and in various media and/or make changes to the Submissions as necessary to conform and adapt them to any requirements or limitations of any networks, devices, services or media.&nbsp; ISLE agrees to use any personal information contained in any of your Submissions in accordance with ISLE's <a href="/pages/privacypolicy.aspx">Privacy Policy​</a>.​</p>
      <p style="text-align: justify;">You agree to pay for all royalties, fees, damages and any other monies owing any person by reason of any Submissions posted by you to or through the Site.</p>
      <p style="text-align: justify;">When you provide Submissions you agree that those Submissions shall not be in violation of the "Unauthorized Activities" paragraph below.&nbsp; Those prohibitions do not require ISLE to monitor, police or remove any Submissions or other information submitted by you or any other user.</p>
      <h3>Unauthorized Activities.</h3>
      <p style="text-align: justify;">When using the Site, you agree not to:</p>
      <ul style="text-align: justify;"><li>Defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others.</li><li>Use racially, ethnically or otherwise offensive language.</li><li>Discuss or incite illegal activity.</li><li>Discuss or engage in political activities.</li><li>Use explicit/obscene language or solicit/post sexually explicit images (actual or simulated).</li><li>Post anything that exploits children or minors or that depicts cruelty to animals.</li><li>Post any copyrighted or trademarked materials without the express permission from the owner.</li><li>Disseminate any unsolicited or unauthorized advertising, promotional materials, 'junk mail', 'spam', 'chain letters', 'pyramid schemes' or any other form of such solicitation.</li><li>Use any robot, spider, scraper or other automated means to access the Site.</li><li>Take any action that imposes an unreasonable or disproportionately large load on our infrastructure.</li><li>Alter the opinions or comments posted by others on the Site.</li></ul>
      <p style="text-align: justify;">This list of prohibitions provides examples and is not complete or exclusive.&nbsp; ISLE reserves the right to (a) terminate access to your account and your ability to post to the Site; and (b) refuse, delete or remove any Submissions; with or without cause and with or without notice, for any reason or no reason, or for any action that ISLE determines is inappropriate or disruptive to the Site or to any other user of the Site. <strong>&nbsp;ISLE may report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct. &nbsp;When legally required or at ISLE's discretion, ISLE will cooperate with law enforcement agencies in any investigation of alleged illegal activity on the Site or on the Internet.</strong></p>
      <p style="text-align: justify;">Unauthorized use of any Materials contained on the Site may violate certain laws and regulations.</p>
      <p style="text-align: justify;"><strong class="ms-rteFontSize-3">Indemnification.</strong></p>
      <p style="text-align: justify;">You agree to indemnify, defend and hold ISLE, Project Sponsors and Project Partners and their respective board members, officers directors, employees, affiliates, agents, licensors, and business partners harmless from and against any and all losses, damages, liabilities, costs, fines, penalties, and expenses (including, without limitation, attorneys' fees and costs of defense) ISLE or any other indemnified party suffers in relation to or arising from your violation of these Terms, your use of the Site or Materials or the use of the Site or Materials by any person using your user name and/or password (including, without limitation, with regard to your participation in the posting areas of the Site or your Submissions).</p>
      <h3>Proprietary Rights.</h3>
      <p style="text-align: justify;">All trademarks, names and logos on the Site are the property of their respective owners.</p>
      <p style="text-align: justify;">Unless otherwise specified in these Terms, all information and screens appearing on the Site, including, without limitation, documents, services, site design, text, graphics, logos, images and icons, as well as the arrangement thereof, are the sole property of ISLE, Copyright © [dates of creation]. All rights not expressly granted herein are reserved.&nbsp; Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of the copyright owner.</p>
      <h3>Intellectual Property Infringement.</h3>
      <p style="text-align: justify;">ISLE respects the intellectual property rights of others, and we ask you to do the same.&nbsp; ISLE has the right to, in appropriate circumstances and at our discretion, terminate service and/or access to the Site for users who infringe the intellectual property rights of others.&nbsp; If you believe that your work is the subject of copyright infringement and/or trademark infringement and appears on our Site, please provide ISLE's designated agent the following information:</p>
      <ul style="text-align: justify;"><li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li></ul>
      <ul style="text-align: justify;"><li>Identification of the copyrighted and/or trademarked work claimed to have been infringed, or, if multiple works at a single online site are covered by a single notification, a representative list of such works at that site.</li></ul>
      <ul style="text-align: justify;"><li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled at the Site, and information reasonably sufficient to permit ISLE to locate the material.</li></ul>
      <ul style="text-align: justify;"><li>Information reasonably sufficient to permit ISLE to contact you as the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted.</li></ul>
      <ul style="text-align: justify;"><li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright and/or trademark owner, its agent or the law.</li></ul>
      <ul style="text-align: justify;"><li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li></ul>
      <p style="text-align: justify;">ISLE's agent for notice of claims of copyright or trademark infringement on the Site can be reached as follows: <a href="mailto:info@ilsharedlearning.org">info@ilsharedlearning.org</a>.&nbsp;</p>
      <p style="text-align: justify;">Please also note that for copyright infringements under Section 512(f) of the Copyright Act, any person who knowingly materially misrepresents that material or activity is infringing may be subject to liability.<br></p>
      <p style="text-align: justify; text-decoration: underline;"><span style="text-decoration: underline;"><strong>Submitting a DMCA Counter-Notification</strong></span></p>
      <p style="text-align: justify;">We will notify you that we have removed or disabled access to copyright-protected material that you provided, if such removal is pursuant to a valid DMCA take-down notice that we have received. If you receive such notice from us, you may provide us with a counter-notification in writing to ISLE designated agent that includes all of the following information:</p>
      <ol style="text-align: justify;"><li>Your physical or electronic signature;</li><li>Identification of the material that has been removed or to which access has been disabled, and the location at which the material appeared before it was removed or access to it was disabled;</li><li>A statement from you under the penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled; and</li><li>Your name, physical address and telephone number, and a statement that you consent to the jurisdiction of a court for the judicial district in which your physical address is located, or if your physical address is outside of the United States, for any judicial district in which ISLE may be located, and that you will accept service of process from the person who provided notification of allegedly infringing material or an agent of such person.</li></ol>
      <p style="text-align: justify; text-decoration: underline;"><span style="text-decoration: underline;"><strong>Termination of Repeat Infringers</strong></span></p>
      <p style="text-align: justify;">ISLE reserves the right, in its sole discretion, to terminate the account or access of any user who is the subject or repeated DMCA or other infringement notifications.&nbsp;&nbsp; </p>
      <h3>Disclaimer of Warranties.</h3>
      <p style="text-align: justify;">Your use of the Site is at your own risk.&nbsp; The Materials have not been verified or authenticated in whole or in part by ISLE, and they may include inaccuracies or typographical or other errors.&nbsp; ISLE does not warrant the accuracy of timeliness of the Materials contained on the Site.&nbsp; ISLE has no liability for any errors or omissions in the Materials or the Site, whether provided by ISLE, our licensors or suppliers or other users.</p>
      <p style="text-align: justify;">ISLE, FOR ITSELF AND ITS LICENSORS, MAKES NO EXPRESS, IMPLIED OR STATUTORY REPRESENTATIONS, WARRANTIES, OR GUARANTEES IN CONNECTION WITH THE SITE OR THE MATERIALS, INCLUDING, WITHOUT LIMITATION, WITH REGARD TO THE QUALITY, SUITABILITY, TRUTH, ACCURACY OR COMPLETENESS OF THE SITE OR THE MATERIALS.&nbsp; UNLESS OTHERWISE EXPLICITLY STATED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SITE AND THE MATERIALS ARE PROVIDED TO YOU ON AN "AS IS," "AS AVAILABLE" AND "WHERE-IS" BASIS WITH NO WARRANTY OF IMPLIED WARRANTIES OF ANY KIND, INCLUDING, WITHOUT LIMITATION, NO WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.&nbsp; ISLE DOES NOT PROVIDE ANY WARRANTIES AGAINST VIRUSES, SPYWARE OR MALWARE THAT MAY BE INSTALLED ON YOUR COMPUTER.</p>
      <h3>Limitation of Liability.</h3>
      <p style="text-align: justify;">ISLE SHALL NOT BE LIABLE TO YOU FOR ANY DAMAGES RESULTING FROM THESE TERMS, THE SITE OR THE MATERIALS, INCLUDING, WITHOUT LIMITATION, YOUR DISPLAYING, COPYING, OR DOWNLOADING ANY MATERIALS TO OR FROM THE SITE OR USE OF THE SITE.&nbsp; IN NO EVENT SHALL ISLE BE LIABLE TO YOU FOR ANY INDIRECT, EXTRAORDINARY, EXEMPLARY, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE) HOWEVER ARISING, EVEN IF ISLE KNOWS THERE IS A POSSIBILITY OF SUCH DAMAGE.&nbsp; ISLE'S LIABILITY TO YOU MAY BE FURTHER LIMITED BY APPLICABLE LAW.</p>
      <h3>Local Laws; Export Control.</h3>
      <p style="text-align: justify;">ISLE controls and operates the Site from its operations in the United States of America and the Materials may not be appropriate or available for use in other locations.&nbsp; If you use the Site outside the United States of America, you are responsible for following applicable local laws.</p>
      <h3>Feedback.</h3>
      <p style="text-align: justify;">If you send or transmit any communications, comments, questions, suggestions or related materials to ISLE, whether by letter, email, telephone or otherwise (collectively, "<strong>Feedback</strong>"), suggesting or recommending changes to the Site or Materials, including, without limitation, new features or functionality relating thereto, all such Feedback is, and will be treated as, non-confidential and non-proprietary.&nbsp; You hereby assign all right, title, and interest in and ISLE is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including, without limitation, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, products and services using such Feedback.&nbsp; You understand and agree that ISLE is not obligated to use, display, reproduce or distribute any such ideas, know-how, concepts or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction or distribution.</p>
      <h3>Choice of Law and Venue.</h3>
      <p style="text-align: justify;">These Terms shall be governed, construed and interpreted in accordance with the laws of the State of Illinois in accordance with the Illinois Court of Claims Act, without giving effect to principles of conflict of laws.&nbsp; You consent to the exclusive jurisdiction and venue of the courts of Illinois, in accordance with the Illinois Court of Claims Act.</p>
      <h3>Contact Us.</h3>
      <p style="text-align: justify;">If you have any questions about these Terms or otherwise need to contact ISLE for any reason, you can reach us at <a href="mailto:info@ilsharedlearning.org">info@ilsharedlearning.org</a>.​</p>

    </div><!--/policy-->
  </div><!--/content-->
</asp:Content>