USE [master]
GO

/****** Object:  Database [LinkChecker]    Script Date: 9/27/2015 11:17:17 AM ******/
CREATE DATABASE [LinkChecker] ON  PRIMARY 
( NAME = N'LinkChecker', FILENAME = N'C:\sql2008Data\Data\LinkChecker.mdf' , SIZE = 36864KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LinkChecker_log', FILENAME = N'C:\sql2008Data\Logs\LinkChecker_log.ldf' , SIZE = 123648KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LinkChecker] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LinkChecker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LinkChecker] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LinkChecker] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LinkChecker] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LinkChecker] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LinkChecker] SET ARITHABORT OFF 
GO

ALTER DATABASE [LinkChecker] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LinkChecker] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LinkChecker] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LinkChecker] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LinkChecker] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LinkChecker] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LinkChecker] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LinkChecker] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LinkChecker] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LinkChecker] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LinkChecker] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LinkChecker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LinkChecker] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LinkChecker] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LinkChecker] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LinkChecker] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LinkChecker] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LinkChecker] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LinkChecker] SET RECOVERY FULL 
GO

ALTER DATABASE [LinkChecker] SET  MULTI_USER 
GO

ALTER DATABASE [LinkChecker] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LinkChecker] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LinkChecker] SET  READ_WRITE 
GO


