//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_SubscriptionType
    {
        public Codes_SubscriptionType()
        {
            this.Library_Subscription = new HashSet<Library_Subscription>();
            this.Library_SectionSubscription = new HashSet<Library_SectionSubscription>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<Library_Subscription> Library_Subscription { get; set; }
        public virtual ICollection<Library_SectionSubscription> Library_SectionSubscription { get; set; }
    }
}
