//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public Content()
        {
            this.Content_History = new HashSet<Content_History>();
            this.Content_Reference = new HashSet<Content_Reference>();
            this.Content_Supplement = new HashSet<Content_Supplement>();
            this.Content_Resource = new HashSet<Content_Resource>();
            this.Content1 = new HashSet<Content>();
            this.Content_Like = new HashSet<Content_Like>();
            this.Content_Partner = new HashSet<Content_Partner>();
            this.Content_Standard = new HashSet<Content_Standard>();
            this.Content_Subscription = new HashSet<Content_Subscription>();
            this.Content_Tag = new HashSet<Content_Tag>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PrivilegeTypeId { get; set; }
        public Nullable<int> ConditionsOfUseId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> IsOrgContentOwner { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> ResourceVersionId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public System.Guid RowId { get; set; }
        public string UseRightsUrl { get; set; }
        public Nullable<System.Guid> DocumentRowId { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> ResourceIntId { get; set; }
        public string Timeframe { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Codes_ContentPrivilege Codes_ContentPrivilege { get; set; }
        public virtual Codes_ContentStatus Codes_ContentStatus { get; set; }
        public virtual ICollection<Content_History> Content_History { get; set; }
        public virtual ICollection<Content_Reference> Content_Reference { get; set; }
        public virtual ICollection<Content_Supplement> Content_Supplement { get; set; }
        public virtual ContentType ContentType { get; set; }
        public virtual ICollection<Content_Resource> Content_Resource { get; set; }
        public virtual ICollection<Content> Content1 { get; set; }
        public virtual Content Content2 { get; set; }
        public virtual ICollection<Content_Like> Content_Like { get; set; }
        public virtual ICollection<Content_Partner> Content_Partner { get; set; }
        public virtual ICollection<Content_Standard> Content_Standard { get; set; }
        public virtual ICollection<Content_Subscription> Content_Subscription { get; set; }
        public virtual ICollection<Content_Tag> Content_Tag { get; set; }
        public virtual Document_Version Document_Version { get; set; }
    }
}
