//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content_RelatedStandard
    {
        public int ContentId { get; set; }
        public int ContentStandardId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Content_Standard Content_Standard { get; set; }
    }
}
