//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content_RelatedStandardsSummary
    {
        public int ContentStandardId { get; set; }
        public int ContentId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int StandardId { get; set; }
        public string StandardUrl { get; set; }
        public string NotationCode { get; set; }
        public string Description { get; set; }
        public int AlignmentTypeCodeId { get; set; }
        public string AlignmentType { get; set; }
        public int UsageTypeId { get; set; }
        public string StandardUsage { get; set; }
        public int IsDirectStandard { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ResourceIntId { get; set; }
        public System.DateTime RelatedStandardCreated { get; set; }
        public int CreatedById { get; set; }
    }
}
