//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GatewayEntities : DbContext
    {
        public GatewayEntities()
            : base("name=GatewayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppGroup> AppGroups { get; set; }
        public DbSet<AppGroup_Member> AppGroup_Member { get; set; }
        public DbSet<AppGroup_OrgMember> AppGroup_OrgMember { get; set; }
        public DbSet<AppGroup_Privilege> AppGroup_Privilege { get; set; }
        public DbSet<AppGroup_RelatedObject> AppGroup_RelatedObject { get; set; }
        public DbSet<ApplicationObject> ApplicationObjects { get; set; }
        public DbSet<AppVisitLog> AppVisitLogs { get; set; }
        public DbSet<Codes_AuthorizationLevel> Codes_AuthorizationLevel { get; set; }
        public DbSet<Codes_ExternalSite> Codes_ExternalSite { get; set; }
        public DbSet<Codes_GroupType> Codes_GroupType { get; set; }
        public DbSet<Codes_OrgMemberRole> Codes_OrgMemberRole { get; set; }
        public DbSet<Codes_OrgMemberType> Codes_OrgMemberType { get; set; }
        public DbSet<Codes_OrgType> Codes_OrgType { get; set; }
        public DbSet<Codes_PrivilegeDepth> Codes_PrivilegeDepth { get; set; }
        public DbSet<Codes_PrivilegeType> Codes_PrivilegeType { get; set; }
        public DbSet<Codes_PublishingRole> Codes_PublishingRole { get; set; }
        public DbSet<Codes_State> Codes_State { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Organization_Member> Organization_Member { get; set; }
        public DbSet<Organization_MemberRole> Organization_MemberRole { get; set; }
        public DbSet<OrganizationRequest> OrganizationRequests { get; set; }
        public DbSet<SqlQuery> SqlQueries { get; set; }
        public DbSet<Organization_MemberCrosstab> Organization_MemberCrosstab { get; set; }
        public DbSet<Organization_MemberSummary> Organization_MemberSummary { get; set; }
        public DbSet<Organization_AdminMembers> Organization_AdminMembers { get; set; }
        public DbSet<OrganizationMember_RoleIdCSV> OrganizationMember_RoleIdCSV { get; set; }
    }
}
