//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsleContentEntities : DbContext
    {
        public IsleContentEntities()
            : base("name=IsleContentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Codes_ContentPrivilege> Codes_ContentPrivilege { get; set; }
        public DbSet<Codes_ContentStatus> Codes_ContentStatus { get; set; }
        public DbSet<Codes_SubscriptionType> Codes_SubscriptionType { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Content_History> Content_History { get; set; }
        public DbSet<Content_Reference> Content_Reference { get; set; }
        public DbSet<Content_Supplement> Content_Supplement { get; set; }
        public DbSet<ContentTemplate> ContentTemplates { get; set; }
        public DbSet<ContentType> ContentTypes { get; set; }
        public DbSet<Document_Version> Document_Version { get; set; }
        public DbSet<Library> Libraries { get; set; }
        public DbSet<Library_Resource> Library_Resource { get; set; }
        public DbSet<Library_Section> Library_Section { get; set; }
        public DbSet<Library_SectionSubscription> Library_SectionSubscription { get; set; }
        public DbSet<Library_SectionType> Library_SectionType { get; set; }
        public DbSet<Library_Subscription> Library_Subscription { get; set; }
        public DbSet<Library_Type> Library_Type { get; set; }
        public DbSet<Library_Party> Library_Party { get; set; }
        public DbSet<Codes_AccessRights> Codes_AccessRights { get; set; }
        public DbSet<Codes_AudienceType> Codes_AudienceType { get; set; }
        public DbSet<Codes_GradeLevel> Codes_GradeLevel { get; set; }
        public DbSet<Codes_ResourceFormat> Codes_ResourceFormat { get; set; }
        public DbSet<Codes_ResourceType> Codes_ResourceType { get; set; }
        public DbSet<ContentSummaryView> ContentSummaryViews { get; set; }
        public DbSet<Library_SectionResourceSummary> Library_SectionResourceSummary { get; set; }
        public DbSet<Library_Comment> Library_Comment { get; set; }
        public DbSet<Library_Like> Library_Like { get; set; }
        public DbSet<Library_SectionComment> Library_SectionComment { get; set; }
        public DbSet<Library_SectionLike> Library_SectionLike { get; set; }
        public DbSet<Library_Invitation> Library_Invitation { get; set; }
        public DbSet<Library_PartyComment> Library_PartyComment { get; set; }
        public DbSet<ContentFile> ContentFiles { get; set; }
        public DbSet<Codes_LibraryAccessLevel> Codes_LibraryAccessLevel { get; set; }
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<Codes_LibraryMemberType> Codes_LibraryMemberType { get; set; }
        public DbSet<Library_Member> Library_Member { get; set; }
        public DbSet<Library_SectionMember> Library_SectionMember { get; set; }
        public DbSet<Person_Following> Person_Following { get; set; }
        public DbSet<Community> Communities { get; set; }
        public DbSet<Community_Member> Community_Member { get; set; }
        public DbSet<Community_Posting> Community_Posting { get; set; }
        public DbSet<Community_PostingDocument> Community_PostingDocument { get; set; }
    }
}
