//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsleContentEntities : DbContext
    {
        public IsleContentEntities()
            : base("name=IsleContentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Codes_ContentPrivilege> Codes_ContentPrivilege { get; set; }
        public DbSet<Codes_ContentStatus> Codes_ContentStatus { get; set; }
        public DbSet<Codes_SubscriptionType> Codes_SubscriptionType { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Content_History> Content_History { get; set; }
        public DbSet<Content_Reference> Content_Reference { get; set; }
        public DbSet<Content_Supplement> Content_Supplement { get; set; }
        public DbSet<ContentTemplate> ContentTemplates { get; set; }
        public DbSet<ContentType> ContentTypes { get; set; }
        public DbSet<Document_Version> Document_Version { get; set; }
        public DbSet<Library> Libraries { get; set; }
        public DbSet<Library_Resource> Library_Resource { get; set; }
        public DbSet<Library_Section> Library_Section { get; set; }
        public DbSet<Library_SectionSubscription> Library_SectionSubscription { get; set; }
        public DbSet<Library_SectionType> Library_SectionType { get; set; }
        public DbSet<Library_Subscription> Library_Subscription { get; set; }
        public DbSet<Library_Type> Library_Type { get; set; }
        public DbSet<Library_Party> Library_Party { get; set; }
        public DbSet<Codes_AccessRights> Codes_AccessRights { get; set; }
        public DbSet<Codes_AudienceType> Codes_AudienceType { get; set; }
        public DbSet<Codes_GradeLevel> Codes_GradeLevel { get; set; }
        public DbSet<Codes_ResourceFormat> Codes_ResourceFormat { get; set; }
        public DbSet<Codes_ResourceType> Codes_ResourceType { get; set; }
        public DbSet<ContentSummaryView> ContentSummaryViews { get; set; }
        public DbSet<Library_SectionResourceSummary> Library_SectionResourceSummary { get; set; }
        public DbSet<Library_Comment> Library_Comment { get; set; }
        public DbSet<Library_Like> Library_Like { get; set; }
        public DbSet<Library_SectionComment> Library_SectionComment { get; set; }
        public DbSet<Library_SectionLike> Library_SectionLike { get; set; }
        public DbSet<Library_PartyComment> Library_PartyComment { get; set; }
        public DbSet<Codes_LibraryAccessLevel> Codes_LibraryAccessLevel { get; set; }
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<Codes_LibraryMemberType> Codes_LibraryMemberType { get; set; }
        public DbSet<Library_Member> Library_Member { get; set; }
        public DbSet<Library_SectionMember> Library_SectionMember { get; set; }
        public DbSet<Person_Following> Person_Following { get; set; }
        public DbSet<Community> Communities { get; set; }
        public DbSet<Community_Member> Community_Member { get; set; }
        public DbSet<Community_PostingDocument> Community_PostingDocument { get; set; }
        public DbSet<Community_PostingSummary> Community_PostingSummary { get; set; }
        public DbSet<Community_Posting> Community_Posting { get; set; }
        public DbSet<Community_PostItem> Community_PostItem { get; set; }
        public DbSet<Content_Resource> Content_Resource { get; set; }
        public DbSet<Codes_CareerCluster> Codes_CareerCluster { get; set; }
        public DbSet<Gateway_OrgSummary> Gateway_OrgSummary { get; set; }
        public DbSet<LR_ConditionOfUse_Select> LR_ConditionOfUse_Select { get; set; }
        public DbSet<LR_PatronOrgSummary> LR_PatronOrgSummary { get; set; }
        public DbSet<ContentNodeSummary> ContentNodeSummaries { get; set; }
        public DbSet<Resource_Standard> Resource_Standard { get; set; }
        public DbSet<ContentConnector_ChildSummary> ContentConnector_ChildSummary { get; set; }
        public DbSet<Curriculum_HierarchySummary> Curriculum_HierarchySummary { get; set; }
        public DbSet<Library_Invitation> Library_Invitation { get; set; }
        public DbSet<LR_ResourceVersion_Summary> LR_ResourceVersion_Summary { get; set; }
        public DbSet<Library_FollowingSummary> Library_FollowingSummary { get; set; }
        public DbSet<Library_MemberResourceSummary> Library_MemberResourceSummary { get; set; }
        public DbSet<Library_MemberSummary> Library_MemberSummary { get; set; }
        public DbSet<Library_ResourceTagUniqueFilters> Library_ResourceTagUniqueFilters { get; set; }
        public DbSet<Codes_StandardUsage> Codes_StandardUsage { get; set; }
        public DbSet<Content_Like> Content_Like { get; set; }
        public DbSet<Content_Partner> Content_Partner { get; set; }
        public DbSet<Content_Standard> Content_Standard { get; set; }
        public DbSet<Content_Subscription> Content_Subscription { get; set; }
        public DbSet<Content_Tag> Content_Tag { get; set; }
        public DbSet<ContentStandard_Summary> ContentStandard_Summary { get; set; }
        public DbSet<Codes_TagCategoryValue_Summary> Codes_TagCategoryValue_Summary { get; set; }
        public DbSet<Content_TagSummary> Content_TagSummary { get; set; }
        public DbSet<Content_LearningListSummary> Content_LearningListSummary { get; set; }
        public DbSet<LearningList_MembersSummary> LearningList_MembersSummary { get; set; }
        public DbSet<Content_DocumentSummary> Content_DocumentSummary { get; set; }
        public DbSet<Codes_ContentPartnerType> Codes_ContentPartnerType { get; set; }
        public DbSet<Curriculum_DistinctStandards> Curriculum_DistinctStandards { get; set; }
        public DbSet<Community_MemberSummary> Community_MemberSummary { get; set; }
        public DbSet<Content_ChildResourceSummary> Content_ChildResourceSummary { get; set; }
        public DbSet<Codes_PostingType> Codes_PostingType { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Organization_Member> Organization_Member { get; set; }
        public DbSet<Organization_MemberRole> Organization_MemberRole { get; set; }
        public DbSet<OrganizationRequest> OrganizationRequests { get; set; }
        public DbSet<Codes_ObjectMemberType> Codes_ObjectMemberType { get; set; }
        public DbSet<Codes_OrgMemberRole> Codes_OrgMemberRole { get; set; }
        public DbSet<Codes_OrgMemberType> Codes_OrgMemberType { get; set; }
        public DbSet<Codes_OrgType> Codes_OrgType { get; set; }
        public DbSet<Codes_PublishingRole> Codes_PublishingRole { get; set; }
        public DbSet<AppGroup> AppGroups { get; set; }
        public DbSet<AppGroup_Member> AppGroup_Member { get; set; }
        public DbSet<AppGroup_OrgMember> AppGroup_OrgMember { get; set; }
        public DbSet<AppGroup_Privilege> AppGroup_Privilege { get; set; }
        public DbSet<AppGroup_RelatedObject> AppGroup_RelatedObject { get; set; }
        public DbSet<ApplicationObject> ApplicationObjects { get; set; }
        public DbSet<Codes_GroupType> Codes_GroupType { get; set; }
        public DbSet<Object_Member> Object_Member { get; set; }
        public DbSet<Codes_AuthorizationLevel> Codes_AuthorizationLevel { get; set; }
        public DbSet<Codes_ExternalSite> Codes_ExternalSite { get; set; }
        public DbSet<Codes_PrivilegeDepth> Codes_PrivilegeDepth { get; set; }
        public DbSet<Codes_PrivilegeType> Codes_PrivilegeType { get; set; }
        public DbSet<Codes_State> Codes_State { get; set; }
        public DbSet<Organization_MemberSummary> Organization_MemberSummary { get; set; }
        public DbSet<AppVisitLog> AppVisitLogs { get; set; }
        public DbSet<SqlQuery> SqlQueries { get; set; }
        public DbSet<Organization_AdminMembers> Organization_AdminMembers { get; set; }
        public DbSet<Organization_MemberCrosstab> Organization_MemberCrosstab { get; set; }
        public DbSet<OrganizationMember_RoleIdCSV> OrganizationMember_RoleIdCSV { get; set; }
        public DbSet<Content_RelatedStandard> Content_RelatedStandard { get; set; }
        public DbSet<Content_RelatedStandardsSummary> Content_RelatedStandardsSummary { get; set; }
        public DbSet<Content_Keyword> Content_Keyword { get; set; }
    }
}
