//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningList_MembersSummary
    {
        public int ContentId { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeId { get; set; }
        public int UserId { get; set; }
        public int PartnerTypeId { get; set; }
        public string PartnerType { get; set; }
        public System.DateTime PartnerCreated { get; set; }
        public System.DateTime PartnerLastUpdated { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Organization { get; set; }
    }
}
