//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Party
    {
        public int Id { get; set; }
        public System.Guid ParentRowId { get; set; }
        public System.Guid RelatedRowId { get; set; }
        public System.DateTime Created { get; set; }
    }
}
