//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public Library()
        {
            this.Library_Section = new HashSet<Library_Section>();
            this.Library_Subscription = new HashSet<Library_Subscription>();
            this.Library_Comment = new HashSet<Library_Comment>();
            this.Library_Like = new HashSet<Library_Like>();
            this.Library_Invitation = new HashSet<Library_Invitation>();
            this.Library_Member = new HashSet<Library_Member>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> LibraryTypeId { get; set; }
        public Nullable<bool> IsDiscoverable { get; set; }
        public Nullable<bool> IsPublic { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public int PublicAccessLevel { get; set; }
        public int OrgAccessLevel { get; set; }
    
        public virtual ICollection<Library_Section> Library_Section { get; set; }
        public virtual ICollection<Library_Subscription> Library_Subscription { get; set; }
        public virtual Library_Type Library_Type { get; set; }
        public virtual ICollection<Library_Comment> Library_Comment { get; set; }
        public virtual ICollection<Library_Like> Library_Like { get; set; }
        public virtual ICollection<Library_Invitation> Library_Invitation { get; set; }
        public virtual Codes_LibraryAccessLevel Codes_LibraryAccessLevel { get; set; }
        public virtual Codes_LibraryAccessLevel Codes_LibraryAccessLevel1 { get; set; }
        public virtual ICollection<Library_Member> Library_Member { get; set; }
    }
}
