//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library_Invitation
    {
        public int Id { get; set; }
        public Nullable<int> LibraryId { get; set; }
        public System.Guid RowId { get; set; }
        public string InvitationType { get; set; }
        public string PassCode { get; set; }
        public string TargetEmail { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public Nullable<int> AddToOrgId { get; set; }
        public Nullable<int> AddAsOrgMemberTypeId { get; set; }
        public string OrgMbrRoles { get; set; }
        public string Subject { get; set; }
        public string MessageContent { get; set; }
        public string EmailNoticeCode { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> DeleteOnResponse { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public Nullable<int> LibMemberTypeId { get; set; }
        public string StartingUrl { get; set; }
    
        public virtual Library Library { get; set; }
    }
}
