//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoerContentBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Organization_Member = new HashSet<Organization_Member>();
            this.OrganizationRequests = new HashSet<OrganizationRequest>();
            this.AppGroups = new HashSet<AppGroup>();
            this.AppGroup_Member = new HashSet<AppGroup_Member>();
            this.AppGroup_OrgMember = new HashSet<AppGroup_OrgMember>();
            this.Contents = new HashSet<Content>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrgTypeId { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MainPhone { get; set; }
        public string MainExtension { get; set; }
        public string Fax { get; set; }
        public string TTY { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string LogoUrl { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Zipcode4 { get; set; }
        public string K12Identifier { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public Nullable<System.Guid> RowId { get; set; }
        public Nullable<bool> IsIsleMember { get; set; }
        public string EmailDomain { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsContentApprovalRequired { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual ICollection<Organization_Member> Organization_Member { get; set; }
        public virtual Organization Organization1 { get; set; }
        public virtual Organization Organization2 { get; set; }
        public virtual ICollection<OrganizationRequest> OrganizationRequests { get; set; }
        public virtual ICollection<AppGroup> AppGroups { get; set; }
        public virtual ICollection<AppGroup_Member> AppGroup_Member { get; set; }
        public virtual ICollection<AppGroup_OrgMember> AppGroup_OrgMember { get; set; }
        public virtual ICollection<Content> Contents { get; set; }
    }
}
