//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GatewayBusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRolePrivilege
    {
        public int RoleId { get; set; }
        public int ObjectId { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> Create { get; set; }
        public Nullable<int> Read { get; set; }
        public Nullable<int> Write { get; set; }
        public Nullable<int> Delete { get; set; }
        public Nullable<int> Append { get; set; }
        public Nullable<int> AppendTo { get; set; }
        public Nullable<int> Assign { get; set; }
        public Nullable<int> Approve { get; set; }
        public Nullable<int> Share { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<short> RoleCode { get; set; }
    
        public virtual ApplicationObject ApplicationObject { get; set; }
    }
}
