USE [master]
GO

/****** Object:  Database [Gateway]    Script Date: 3/9/2014 9:21:45 PM ******/
CREATE DATABASE [Gateway] ON  PRIMARY 
( NAME = N'Gateway', FILENAME = N'C:\sql2008Data\Data\Gateway.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Gateway_log', FILENAME = N'C:\sql2008Data\Logs\Gateway_log.ldf' , SIZE = 5120KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Gateway] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gateway].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gateway] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gateway] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gateway] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gateway] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gateway] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gateway] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gateway] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Gateway] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gateway] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gateway] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gateway] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gateway] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gateway] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gateway] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gateway] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gateway] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gateway] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gateway] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gateway] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gateway] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gateway] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gateway] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gateway] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gateway] SET RECOVERY FULL 
GO

ALTER DATABASE [Gateway] SET  MULTI_USER 
GO

ALTER DATABASE [Gateway] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gateway] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gateway] SET  READ_WRITE 
GO


