USE [master]
GO

/****** Object:  Database [IsleContent]    Script Date: 3/9/2014 9:23:01 PM ******/
CREATE DATABASE [IsleContent] ON  PRIMARY 
( NAME = N'IsleContent', FILENAME = N'C:\sql2008Data\Data\IsleContent.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IsleContent_log', FILENAME = N'C:\sql2008Data\Logs\IsleContent_log.ldf' , SIZE = 26944KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [IsleContent] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IsleContent].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IsleContent] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IsleContent] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IsleContent] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IsleContent] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IsleContent] SET ARITHABORT OFF 
GO

ALTER DATABASE [IsleContent] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IsleContent] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [IsleContent] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IsleContent] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IsleContent] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IsleContent] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IsleContent] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IsleContent] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IsleContent] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IsleContent] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IsleContent] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IsleContent] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IsleContent] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IsleContent] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IsleContent] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IsleContent] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IsleContent] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IsleContent] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IsleContent] SET RECOVERY FULL 
GO

ALTER DATABASE [IsleContent] SET  MULTI_USER 
GO

ALTER DATABASE [IsleContent] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IsleContent] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IsleContent] SET  READ_WRITE 
GO


