//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILPathways.FaqServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.illinoisworknet.com/Services/Faqs/", ConfigurationName="FaqServiceReference.FaqServiceSoap")]
    public interface FaqServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/FaqsByCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FaqsByCategory(string category, string keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Search(string pFilter, string pOrderBy, int pStartPageIndex, int pMaximumRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/PostQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PostQuestion(string question, string category, string createdByEmail, string defaultTargetPathways, string passcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/ConfirmQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConfirmQuestion(string questionId, string passcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/UpdateQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateQuestion(ILPathways.FaqServiceReference.FaqItem faq, string passcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/Services/Faqs/FaqGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ILPathways.FaqServiceReference.FaqItem FaqGet(string faqId, string passcode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.illinoisworknet.com/Services/Faqs/")]
    public partial class FaqItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.Guid rowIdField;
        
        private string faqCodeField;
        
        private string titleField;
        
        private string descriptionField;
        
        private int categoryIdField;
        
        private int subcategoryIdField;
        
        private string statusField;
        
        private int sequenceNbrField;
        
        private int pathwayIdField;
        
        private int hitsField;
        
        private int createdByIdField;
        
        private string createdByField;
        
        private System.DateTime createdField;
        
        private int lastUpdatedByIdField;
        
        private string lastUpdatedByField;
        
        private System.DateTime lastUpdatedField;
        
        private bool isActiveField;
        
        private bool isValidField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
                this.RaisePropertyChanged("RowId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FaqCode {
            get {
                return this.faqCodeField;
            }
            set {
                this.faqCodeField = value;
                this.RaisePropertyChanged("FaqCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int SubcategoryId {
            get {
                return this.subcategoryIdField;
            }
            set {
                this.subcategoryIdField = value;
                this.RaisePropertyChanged("SubcategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SequenceNbr {
            get {
                return this.sequenceNbrField;
            }
            set {
                this.sequenceNbrField = value;
                this.RaisePropertyChanged("SequenceNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int PathwayId {
            get {
                return this.pathwayIdField;
            }
            set {
                this.pathwayIdField = value;
                this.RaisePropertyChanged("PathwayId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Hits {
            get {
                return this.hitsField;
            }
            set {
                this.hitsField = value;
                this.RaisePropertyChanged("Hits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CreatedById {
            get {
                return this.createdByIdField;
            }
            set {
                this.createdByIdField = value;
                this.RaisePropertyChanged("CreatedById");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int LastUpdatedById {
            get {
                return this.lastUpdatedByIdField;
            }
            set {
                this.lastUpdatedByIdField = value;
                this.RaisePropertyChanged("LastUpdatedById");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string LastUpdatedBy {
            get {
                return this.lastUpdatedByField;
            }
            set {
                this.lastUpdatedByField = value;
                this.RaisePropertyChanged("LastUpdatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
                this.RaisePropertyChanged("LastUpdated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("IsValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FaqServiceSoapChannel : ILPathways.FaqServiceReference.FaqServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaqServiceSoapClient : System.ServiceModel.ClientBase<ILPathways.FaqServiceReference.FaqServiceSoap>, ILPathways.FaqServiceReference.FaqServiceSoap {
        
        public FaqServiceSoapClient() {
        }
        
        public FaqServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaqServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaqServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaqServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet FaqsByCategory(string category, string keywords) {
            return base.Channel.FaqsByCategory(category, keywords);
        }
        
        public System.Data.DataSet Search(string pFilter, string pOrderBy, int pStartPageIndex, int pMaximumRows) {
            return base.Channel.Search(pFilter, pOrderBy, pStartPageIndex, pMaximumRows);
        }
        
        public string PostQuestion(string question, string category, string createdByEmail, string defaultTargetPathways, string passcode) {
            return base.Channel.PostQuestion(question, category, createdByEmail, defaultTargetPathways, passcode);
        }
        
        public string ConfirmQuestion(string questionId, string passcode) {
            return base.Channel.ConfirmQuestion(questionId, passcode);
        }
        
        public string UpdateQuestion(ILPathways.FaqServiceReference.FaqItem faq, string passcode) {
            return base.Channel.UpdateQuestion(faq, passcode);
        }
        
        public ILPathways.FaqServiceReference.FaqItem FaqGet(string faqId, string passcode) {
            return base.Channel.FaqGet(faqId, passcode);
        }
    }
}
