//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILPathways.workNetGlossary {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.illinoisworknet.com/webServices/GlossaryWS/", ConfigurationName="workNetGlossary.GlossaryWSSoap")]
    public interface GlossaryWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/webServices/GlossaryWS/GetByTerm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ILPathways.workNetGlossary.Glossary GetByTerm(string term, string library);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/webServices/GlossaryWS/GetById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ILPathways.workNetGlossary.Glossary GetById(int glossaryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.illinoisworknet.com/webServices/GlossaryWS/GetByTermDS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetByTermDS(string term, string library);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.illinoisworknet.com/webServices/GlossaryWS/")]
    public partial class Glossary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string termField;
        
        private string descriptionField;
        
        private string libraryField;
        
        private bool isAliasField;
        
        private bool isAcronymField;
        
        private int parentTermIdField;
        
        private string parentTermField;
        
        private string parentDescriptionField;
        
        private bool isValidField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
                this.RaisePropertyChanged("Term");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Library {
            get {
                return this.libraryField;
            }
            set {
                this.libraryField = value;
                this.RaisePropertyChanged("Library");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsAlias {
            get {
                return this.isAliasField;
            }
            set {
                this.isAliasField = value;
                this.RaisePropertyChanged("IsAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsAcronym {
            get {
                return this.isAcronymField;
            }
            set {
                this.isAcronymField = value;
                this.RaisePropertyChanged("IsAcronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ParentTermId {
            get {
                return this.parentTermIdField;
            }
            set {
                this.parentTermIdField = value;
                this.RaisePropertyChanged("ParentTermId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ParentTerm {
            get {
                return this.parentTermField;
            }
            set {
                this.parentTermField = value;
                this.RaisePropertyChanged("ParentTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ParentDescription {
            get {
                return this.parentDescriptionField;
            }
            set {
                this.parentDescriptionField = value;
                this.RaisePropertyChanged("ParentDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("IsValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GlossaryWSSoapChannel : ILPathways.workNetGlossary.GlossaryWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GlossaryWSSoapClient : System.ServiceModel.ClientBase<ILPathways.workNetGlossary.GlossaryWSSoap>, ILPathways.workNetGlossary.GlossaryWSSoap {
        
        public GlossaryWSSoapClient() {
        }
        
        public GlossaryWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GlossaryWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlossaryWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GlossaryWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ILPathways.workNetGlossary.Glossary GetByTerm(string term, string library) {
            return base.Channel.GetByTerm(term, library);
        }
        
        public ILPathways.workNetGlossary.Glossary GetById(int glossaryId) {
            return base.Channel.GetById(glossaryId);
        }
        
        public System.Data.DataSet GetByTermDS(string term, string library) {
            return base.Channel.GetByTermDS(term, library);
        }
    }
}
